"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "everforest"

format = """
$line_break\
$hostname\
$directory\
$line_break\
$character\
"""

right_format = """
$git_branch\
$git_status
"""

# ---------- HOST（膠囊左）
[hostname]
ssh_only = false
format = "[](fg:bg3)[ $hostname ](fg:blue bg:bg3)[](fg:bg3 bg:bg2)"

# ---------- DIRECTORY（接續）
[directory]
truncation_length = 0
format = "[  $path ](fg:fg bg:bg2)[](fg:bg2)"

# ---------- GIT（右側膠囊）
[git_branch]
symbol = ""
format = "[](fg:green)[ $symbol $branch ](fg:bg0 bg:green)"

[git_status]
format = "[ $all_status$ahead_behind ](fg:bg0 bg:green)[](fg:green)"

# ---------- PROMPT
[character]
success_symbol = "[➜](bold #D3C6AA)"
error_symbol = "[➜](bold red)"

# ---------- DISABLE
[package]
disabled = true

# ---------- LANG
[c]
symbol = ""
format = "[$symbol $name $version](bold blue)"

[cpp]
symbol = ""
format = "[$symbol $name $version](bold blue)"

[lua]
symbol = ""
format = "[$symbol $name $version](bold blue)"

# ---------- EVERFOREST
[palettes.everforest]
bg_dim = "#232a2e"
bg0 = "#2d353b"
bg1 = "#343f44"
bg2 = "#3d484d"
bg3 = "#475258"
bg4 = "#4f585e"
bg5 = "#56635f"

fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
